#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	3
bspc config window_gap          	16

bspc config click_to_focus		true


bspc config focused_border_color 	"#98C7D8"
bspc config normal_border_color 	"#207E8B"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a "Tor Browser" state=floating





